<#
.SYNOPSIS
    Regenerates the IL2CPP dump (dump.cs) from the game's native DLLs.
    Run this script whenever the game updates to refresh the type/method stubs.

.DESCRIPTION
    Uses Il2CppDumper to extract C# stubs from:
      - GameAssembly.dll   (IL2CPP native binary)
      - global-metadata.dat (metadata file generated by Unity's IL2CPP build)

    Output is written to the project's dump\ folder, replacing the old dump.cs.

.NOTES
    Run from PowerShell on Windows (not WSL) with the project root as working directory,
    or just double-click the script and let it prompt.
#>

param (
    [string]$GameDir = "C:\Program Files (x86)\Steam\steamapps\common\Yu-Gi-Oh!  Master Duel"
)

$ErrorActionPreference = "Stop"

# ── Paths ────────────────────────────────────────────────────────────────────

$ScriptDir  = Split-Path $MyInvocation.MyCommand.Path
$ProjectDir = Split-Path $ScriptDir
$DumperExe  = Join-Path $ProjectDir "tools\Il2CppDumper\Il2CppDumper.exe"
$DumpOutDir = Join-Path $ProjectDir "dump"

# IL2CPP binary — next to the game executable
$GameAssembly = Join-Path $GameDir "GameAssembly.dll"

# Metadata — inside the Data folder (name varies: MasterDuel_Data or MasterDuel)
$MetadataCandidates = @(
    (Join-Path $GameDir "MasterDuel_Data\il2cpp_data\Metadata\global-metadata.dat"),
    (Join-Path $GameDir "MasterDuel_Data\Metadata\global-metadata.dat"),
    (Join-Path $GameDir "masterduel_Data\il2cpp_data\Metadata\global-metadata.dat")
)
$GlobalMetadata = $MetadataCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1

# ── Validation ───────────────────────────────────────────────────────────────

if (-not (Test-Path $DumperExe)) {
    Write-Error "Il2CppDumper.exe not found at: $DumperExe"
    exit 1
}
if (-not (Test-Path $GameAssembly)) {
    Write-Error "GameAssembly.dll not found at: $GameAssembly`nIs the game installed at: $GameDir ?"
    exit 1
}
if (-not $GlobalMetadata) {
    Write-Error "global-metadata.dat not found in any expected location under: $GameDir"
    exit 1
}

# ── Output folder ─────────────────────────────────────────────────────────────

if (-not (Test-Path $DumpOutDir)) {
    New-Item -ItemType Directory -Path $DumpOutDir | Out-Null
}

# ── Run Il2CppDumper ─────────────────────────────────────────────────────────

Write-Host ""
Write-Host "=== IL2CPP Dump ===" -ForegroundColor Cyan
Write-Host "GameAssembly : $GameAssembly"
Write-Host "Metadata     : $GlobalMetadata"
Write-Host "Output dir   : $DumpOutDir"
Write-Host ""
Write-Host "Running Il2CppDumper... (this may take a few minutes)" -ForegroundColor Yellow

# Il2CppDumper writes output to the directory where the assembly file is,
# unless we specify a separate output directory as the 3rd argument.
& $DumperExe $GameAssembly $GlobalMetadata $DumpOutDir

if ($LASTEXITCODE -ne 0) {
    Write-Error "Il2CppDumper exited with code $LASTEXITCODE"
    exit 1
}

# ── Verify output ─────────────────────────────────────────────────────────────

$DumpCs = Join-Path $DumpOutDir "dump.cs"
if (Test-Path $DumpCs) {
    $Lines = (Get-Content $DumpCs).Count
    Write-Host ""
    Write-Host "Done! dump.cs written to: $DumpCs ($Lines lines)" -ForegroundColor Green
} else {
    Write-Warning "dump.cs was not found in output directory after dump. Check Il2CppDumper output above."
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Verify dump.cs is up to date (check game version / class names)"
Write-Host "  2. Search for new or changed methods in dump.cs before updating patches"
Write-Host "  3. Run  scripts\Build-Mod.ps1  to rebuild the mod after updating patches"
Write-Host ""
