# Analyze YGO Master Duel interop stubs for menu/UI/navigation-related types.
#
# Uses Assembly-CSharp.dll from BepInEx\interop\ (managed .NET stubs generated by
# BepInEx on first game run — NOT the native GameAssembly.dll which is unusable here).
#
# Usage: powershell -NoProfile -File tools\analyze_core_menus.ps1
# Output: analysis_core_menus.txt at repo root

$ErrorActionPreference = "Stop"

$repoRoot    = Split-Path -Parent $PSScriptRoot
$interopDir  = Join-Path $repoRoot "BepInEx\interop"

# Fallback to game installation if local stubs not present
if (-not (Test-Path $interopDir)) {
    $interopDir = "C:\Program Files (x86)\Steam\steamapps\common\Yu-Gi-Oh!  Master Duel\BepInEx\interop"
}

$assemblyPath = Join-Path $interopDir "Assembly-CSharp.dll"
$outputPath   = Join-Path $repoRoot "analysis_core_menus.txt"

Write-Host "Analyzing: $assemblyPath" -ForegroundColor Cyan

if (-not (Test-Path $assemblyPath)) {
    Write-Host "Assembly not found at $assemblyPath" -ForegroundColor Red
    Write-Host "Run the game at least once with BepInEx installed to generate interop stubs." -ForegroundColor Yellow
    exit 1
}

try {
    . (Join-Path $PSScriptRoot "_interop-loader.ps1")
    $assembly = Load-InteropAssembly $assemblyPath $interopDir
    $types    = Get-AssemblyTypes $assembly

    Write-Host "Total types found: $($types.Count)"

    # YGO-specific menu/UI keywords
    $keywords = @(
        'Menu', 'Dialog', 'Modal', 'Scene', 'Screen', 'Panel',
        'Navigation', 'Button', 'Overlay', 'View', 'Controller',
        'Manager', 'UI', 'Selectable', 'Focus', 'Selector',
        'ViewController', 'SelectionButton', 'Window', 'Popup',
        'YgomGame', 'YgomSystem', 'YgomMiniGame'
    )

    $results = @()
    foreach ($type in $types) {
        $name = $type.FullName
        foreach ($kw in $keywords) {
            if ($name -match $kw) {
                $results += $type
                break
            }
        }
    }

    Write-Host "Matched types: $($results.Count)"

    $output = @()
    $output += "YGO Master Duel — Assembly-CSharp.dll Analysis — Menu/UI/Navigation Types"
    $output += "Generated: $(Get-Date)"
    $output += "Total matched: $($results.Count)"
    $output += "=" * 60
    $output += ""

    foreach ($type in ($results | Sort-Object FullName)) {
        $output += "CLASS: $($type.FullName)"
        if ($type.BaseType) {
            $output += "  Base: $($type.BaseType.Name)"
        }
        $output += "  IsInterface: $($type.IsInterface)"
        $output += "  Public: $($type.IsPublic)"

        try {
            $props = $type.GetProperties(
                [System.Reflection.BindingFlags]::Public -bor
                [System.Reflection.BindingFlags]::Instance -bor
                [System.Reflection.BindingFlags]::Static)
            if ($props.Count -gt 0) {
                $output += "  Properties:"
                foreach ($prop in $props) {
                    $output += "    $($prop.PropertyType.Name) $($prop.Name)"
                }
            }
        } catch {}

        try {
            $methods = $type.GetMethods(
                [System.Reflection.BindingFlags]::Public -bor
                [System.Reflection.BindingFlags]::Instance -bor
                [System.Reflection.BindingFlags]::DeclaredOnly) |
                Where-Object { -not $_.IsSpecialName }
            if ($methods.Count -gt 0) {
                $output += "  Methods:"
                foreach ($method in $methods) {
                    $params = ($method.GetParameters() |
                        ForEach-Object { "$($_.ParameterType.Name) $($_.Name)" }) -join ", "
                    $output += "    $($method.ReturnType.Name) $($method.Name)($params)"
                }
            }
        } catch {}

        $output += "-" * 40
        $output += ""
    }

    $output | Out-File -FilePath $outputPath -Encoding UTF8
    Write-Host "Results written to: $outputPath" -ForegroundColor Green
}
catch {
    Write-Host "Error: $_" -ForegroundColor Red
}
