# Decompile a game type using ilspycmd against the YGO Master Duel interop stubs.
#
# Usage:
#   .\tools\decompile.ps1 "YgomGame.Duel.DuelLP"
#   .\tools\decompile.ps1 "PhaseSelect3D" -Dll Asm
#   .\tools\decompile.ps1 "Engine.Phase" -Dll Asm -OutDir "C:\tmp"
#   .\tools\decompile.ps1 "SomeType" -Dll Auto   # tries Asm, AsmFirst, Generated
#
# NOTE: GameAssembly.dll is a native IL2CPP binary — use the managed interop stubs
#       in BepInEx\interop\ instead. These are generated by BepInEx on first game run.
#
# Output goes to decompiled\interop\<TypeName>\ by default.

param(
    [Parameter(Mandatory=$true, Position=0)]
    [string]$TypeName,

    [Parameter(Position=1)]
    [ValidateSet("Asm", "AsmFirst", "Generated", "Spine", "Auto")]
    [string]$Dll = "Auto",

    [Parameter()]
    [string]$OutDir = ""
)

$ErrorActionPreference = "Stop"

# ── Paths ─────────────────────────────────────────────────────────────────────

$repoRoot   = Split-Path -Parent $PSScriptRoot
$interopDir = Join-Path $repoRoot "BepInEx\interop"
$ilspycmd   = "$env:USERPROFILE\.dotnet\tools\ilspycmd.exe"

# Fallback: game-installed interop stubs
$gameInterop = "C:\Program Files (x86)\Steam\steamapps\common\Yu-Gi-Oh!  Master Duel\BepInEx\interop"
if (-not (Test-Path $interopDir)) {
    $interopDir = $gameInterop
}

if ([string]::IsNullOrEmpty($OutDir)) {
    $OutDir = Join-Path $repoRoot "decompiled\interop"
}

# ── DLL map ───────────────────────────────────────────────────────────────────
# Asm       = Assembly-CSharp.dll    (main game types: YgomGame.*, Engine.*, YgomSystem.*)
# AsmFirst  = Assembly-CSharp-firstpass.dll (utility/early types)
# Generated = __Generated.dll        (IL2CPP-generated glue types)
# Spine     = spine-unity.dll        (Spine animation — rarely needed)

$dllMap = @{
    "Asm"       = Join-Path $interopDir "Assembly-CSharp.dll"
    "AsmFirst"  = Join-Path $interopDir "Assembly-CSharp-firstpass.dll"
    "Generated" = Join-Path $interopDir "__Generated.dll"
    "Spine"     = Join-Path $interopDir "spine-unity.dll"
}

# ── Search order ──────────────────────────────────────────────────────────────

if ($Dll -eq "Auto") {
    $searchOrder = @("Asm", "AsmFirst", "Generated")
} else {
    $searchOrder = @($Dll)
}

# ── Output file ───────────────────────────────────────────────────────────────
# Use just the last segment for shorter filenames (e.g. "DuelLP" from "YgomGame.Duel.DuelLP")

$shortName  = $TypeName.Split('.')[-1]
$typeOutDir = Join-Path $OutDir ($TypeName -replace '\.', '\')
if (-not (Test-Path $typeOutDir)) {
    New-Item -ItemType Directory -Path $typeOutDir -Force | Out-Null
}
$outFile = Join-Path $OutDir "$shortName.cs"

$success = $false

foreach ($dllKey in $searchOrder) {
    $dllPath = $dllMap[$dllKey]

    if (-not (Test-Path $dllPath)) {
        Write-Host "  [SKIP] $dllKey — DLL not found at $dllPath" -ForegroundColor Yellow
        continue
    }

    Write-Host "  [TRY]  $dllKey → $dllPath" -ForegroundColor Cyan

    try {
        # ilspycmd outputs UTF-8 with BOM on some versions — pipe through Out-String to normalise
        $output    = & $ilspycmd $dllPath -t $TypeName 2>&1
        $outputStr = $output | Out-String

        # Check for common failure patterns
        if ($outputStr -match "not find|could not be found") {
            Write-Host "  [MISS] Type not found in $dllKey" -ForegroundColor Yellow
            continue
        }

        # Success = has actual code constructs
        if ($outputStr -match "\b(class|struct|enum|interface|namespace)\b") {
            $outputStr | Out-File -Encoding utf8 $outFile
            Write-Host "  [OK]   Decompiled '$TypeName' from $dllKey → $outFile" -ForegroundColor Green
            $success = $true
            break
        } else {
            Write-Host "  [MISS] No code output from $dllKey" -ForegroundColor Yellow
            if ($dllKey -eq $searchOrder[-1]) {
                Write-Host "  Last output: $($outputStr.Substring(0,[Math]::Min(200,$outputStr.Length)))" -ForegroundColor DarkGray
            }
        }
    } catch {
        Write-Host "  [ERR]  $dllKey → $($_.Exception.Message)" -ForegroundColor Red
    }
}

if (-not $success) {
    Write-Host ""
    Write-Host "  [FAIL] Could not decompile '$TypeName'." -ForegroundColor Red
    Write-Host "  Tried : $($searchOrder -join ', ')" -ForegroundColor Red
    Write-Host "  Hint  : Verify the full type name against dump\dump.cs" -ForegroundColor Yellow
    Write-Host "  Grep  : Select-String -Path '$(Join-Path $repoRoot 'dump\dump.cs')' -Pattern '$shortName'" -ForegroundColor Yellow
    exit 1
}
